// Generated by IcedCoffeeScript 108.0.11
(function() {
  var err, filename, fs, iced, loader, out, source, target, __iced_deferrals, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  loader = require('iced-react-loader');

  fs = require('fs');

  out = console.log;

  filename = process.argv[2];

  if (!filename) {
    throw 'usage: iced-react [filename]';
  }

  (function(_this) {
    return (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "/home/dev/npm/iced-react/src/iced-react.iced"
      });
      fs.readFile(filename, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return source = arguments[1];
          };
        })(),
        lineno: 8
      }));
      __iced_deferrals._fulfill();
    });
  })(this)((function(_this) {
    return function() {
      if (err) {
        throw err;
      }
      target = loader(source.toString());
      return eval(target);
    };
  })(this));

}).call(this);
